export enum CategoryType {
  GENERAL = 'GENERAL',
  HTML = 'HTML',
  CSS = 'CSS',
  JAVASCRIPT = "JAVASCRIPT",
  GIT = 'GIT',
  WEBPACK = 'WEBPACK',
  ALGORITHMS = "ALGORITHMS",
  OTHER = "OTHER",
  REACTJS = "REACTJS",
  VUEJS = "VUEJS",
  ANGULARJS = "ANGULARJS",
  TYPESCRIPT = "TYPESCRIPT",
}

